#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.recurse('bfdloader bfdFrontend')

    bld(features='cxx',
            target = 'objcodeFrontend',
            use = 'loader bfdFrontend ELF_LIB',
            install_path = None
    )
