#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

def build(bld):
    bld.program(source='analyzer.cpp main.cpp',
        target = 'memAnalyzer',
        use = 'utils BOOST BOOST_PROGRAM_OPTIONS BOOST_FILESYSTEM BOOST_SYSTEM',
        includes = '. ../runtime/misc ../runtime/utils'
    )
