#!/bin/bash

#The purpouse of this script is the automation of the simulator creation.
#If all previous steps end correctly, the script runs the tests.

SYSTEMC_PATH=/home/dimi/Scrivania/HIGHproject/download/systemc/
TLM_INCLUDE_PATH=/home/dimi/Scrivania/HIGHproject/download/TLM-2008-06-09/include/

#SYSTEMC_PATH=/usr/lib/systemc
#TLM_INCLUDE_PATH=/usr/lib/tlm/include

COUNT=1
TOTAL=4

echo "WARNING: You have to run this script from the MICROBLAZE directory."
sleep 1
	
clear && echo "step $COUNT/$TOTAL: python MICROBLAZEArch.py"
python MICROBLAZEArch.py
COUNT=$((COUNT+1))
echo "COMPLETED!"

cd processor

clear && echo "step $COUNT/$TOTAL: processor/waf configure --with-systemc=$SYSTEMC_PATH --with-tlm=$TLM_INCLUDE_PATH"
./waf configure --with-systemc=$SYSTEMC_PATH --with-tlm=$TLM_INCLUDE_PATH
COUNT=$((COUNT+1))
echo "COMPLETED!"

clear && echo "step $COUNT/$TOTAL: processor/waf"
./waf
COUNT=$((COUNT+1))
echo "COMPLETED!"

clear && echo "step $COUNT/$TOTAL: tests. In God we trust :)"
_build_/default/funcLT/tests/tests

echo "If all steps are completed without errors, you should feel extremely satisfied. :)"
beep -f 329.6 -l 111 -n -l 111 -f 440 -n -f 544.4 -l 111 -n -f 659.2 -l 166 -n -f 1 -l 88 -n -f 544.4 -l 88 -n -f 659.2 -l 333
