#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.install_files('${PREFIX}/include', 'SparseMemoryLT.hpp MemoryLT.hpp MemoryAT.hpp memAccessType.hpp PINTarget.hpp')
