#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os, Options

def build(bld):
    bld.add_subdirs('runtime memAnalyzer')

    obj = bld.new_task_gen('cxx', 'staticlib')
    obj.add_objects = 'loader syscall bfdFrontend tools debugger utils'
    obj.name = 'trap'
    obj.target = 'trap'
    obj.install_path = os.path.join('${PREFIX}', 'lib')

    obj = bld.new_task_gen('py')
    obj.find_sources_in_dirs('.', exts=['.py'])
    obj.install_path = os.path.join('${PYTHON_INSTALL_DIR}', 'trap')
