#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.recurse('elfloader elfFrontend')

    bld(features='cxx',
            target = 'objcodeFrontend',
            use = 'loader elfFrontend ELF_LIB',
            install_path = None
    )
