#!/usr/bin/env python

import os, Options

def build(bld):
    obj = bld.new_task_gen('py')
    obj.find_sources_in_dirs('.', exts=['.py'])
    if Options.options.pyinstalldir:
        obj.install_path = os.path.join(Options.options.pyinstalldir, 'cxx_writer')
    else:
        obj.install_path = os.path.join(obj.default_install_path, 'cxx_writer')
    bld.add_subdirs('writer_code')
