#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os
from waflib.Task import Task

def installWafFun(ctx):
    if ctx.cmd == 'install':
        import shutil
        shutil.copy2('waf', os.path.join(ctx.env.PYTHONDIR, 'cxx_writer'))
    elif ctx.cmd == 'uninstall':
        try:
            os.remove(os.path.join(ctx.env.PYTHONDIR, 'cxx_writer', 'waf'))
        except:
            pass

def build(bld):
    bld(features='py', source=bld.path.ant_glob('*.py'), install_path = os.path.join('${PYTHONDIR}', 'cxx_writer'))

    bld.recurse('writer_code')

    bld.add_post_fun(post)

def post(ctx):
    if ctx.cmd in ['install', 'uninstall']:
        installWafFun(ctx)
