#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

def build(bld):
    bld.objects(source='profInfo.cpp',
        use = 'BFD SYSTEMC BOOST',
        includes = '. ../utils ../bfdFrontend',
        target = 'profiler',
        install_path = None
    )

    bld.install_files('${PREFIX}/include', 'profiler.hpp profInfo.hpp')
