#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os, Options

def build(bld):
    obj = bld.new_task_gen('cxx')
    obj.source="""
        profInfo.cpp
    """
    obj.uselib = 'BFD SYSTEMC'
    obj.includes = '. ../utils ../bfdFrontend'
    obj.export_incdirs = '.'
    obj.name = 'profiler'
    obj.target = 'profiler'
    obj.install_path = None
    bld.install_files('${PREFIX}/include', 'profiler.hpp profInfo.hpp')
