#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.objects(source='profInfo.cpp',
        use = 'ELF_LIB SYSTEMC BOOST',
        includes = '. ../utils ../bfdFrontend',
        target = 'profiler',
        install_path = None
    )

    bld.install_files(os.path.join(bld.env.PREFIX, 'include'), 'profiler.hpp profInfo.hpp')
