#!/usr/bin/env python

import os, Params

def build(bld):
    obj = bld.new_task_gen('py')
    obj.find_sources_in_dirs('.', exts=['.py'])
    if Params.g_options.pyinstalldir:
        obj.install_path = os.path.join(Params.g_options.pyinstalldir, 'writer_code')
    else:
        obj.install_path = os.path.join(obj.default_install_path, 'writer_code')
