#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld(features='py', source=bld.path.ant_glob('*.py'), install_path = os.path.join(bld.env.PYTHONDIR, 'cxx_writer', 'writer_code'))
