#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os, Options

def build(bld):
    obj = bld.new_task_gen('py')
    obj.find_sources_in_dirs('.', exts=['.py'])
    obj.install_path = os.path.join('${PYTHONDIR}', 'cxx_writer', 'writer_code')
