#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    if bld.env['LICENSE'] == 'gpl':
        elfInclude = '../libbfd_objloader/bfdFrontend'
    else:
        elfInclude = '../libelf_objloader/bfdFrontend'
    
    bld.objects(source='syscCallB.cpp',
        includes = '. ' + elfInclude + ' ../utils ..',
        use = 'SYSTEMC BOOST BOOST_REGEX ELF_LIB',
        target = 'syscall',
        install_path = None
    )
    
    bld.install_files(os.path.join(bld.env.PREFIX, 'include'), 'osEmulator.hpp syscCallB.hpp')
