#!/usr/bin/env python

import os, Options

def build(bld):
    obj = bld.new_task_gen('cxx', 'objects')
    obj.source="""
        syscCallB.cpp
    """
    obj.includes = '.'
    obj.export_incdirs = '.'
    obj.name = 'syscall'
    obj.target = 'syscall'
    obj.install_path = None
    bld.install_files('${PREFIX}/include', 'osEmulator.hpp syscCallB.hpp')
