#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os, Options

def build(bld):
    obj = bld.new_task_gen('cxx', 'objects')
    obj.source="""
        bfdFrontend.cpp
    """
    obj.uselib = 'BFD BOOST BOOST_REGEX'
    obj.includes = '. ../utils'
    obj.export_incdirs = '.'
    obj.name = 'bfdFrontend'
    obj.target = 'bfdFrontend'
    obj.install_path = None
    bld.install_files('${PREFIX}/include', 'bfdFrontend.hpp')
