#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.objects(source='bfdFrontend.cpp',
        use = 'BFD BOOST BOOST_REGEX',
        includes = '. ../utils',
        target = 'bfdFrontend',
        install_path = None
    )
    
    bld.install_files(os.path.join(bld.env.PREFIX, 'include'), 'bfdFrontend.hpp')
