#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os, Options

def build(bld):
    obj = bld.new_task_gen('cxx')
    obj.source="""
        execLoader.cpp
    """
    obj.uselib = 'BFD'
    obj.includes = '. ../utils'
    obj.export_incdirs = '.'
    obj.name = 'loader'
    obj.target = 'loader'
    obj.install_path = None
    bld.install_files('${PREFIX}/include', 'execLoader.hpp')
