#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

def build(bld):
    bld.objects(source='execLoader.cpp', 
        use = 'BFD BOOST BOOST_FILESYSTEM BOOST_SYSTEM',
        includes = '. ../utils',
        target = 'loader', 
        install_path = None
    )

    bld.install_files('${PREFIX}/include', 'execLoader.hpp')
