#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    obj = bld.new_task_gen('cxx')
    obj.source="""
        utils.cpp
    """
    obj.includes = '.'
    obj.export_incdirs = '.'
    obj.name = 'utils'
    obj.target = 'utils'
    obj.install_path = None

    bld.install_files('${PREFIX}/include', 'utils.hpp customExceptions.hpp')
