#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

def build(bld):
    bld.objects(source='trap_utils.cpp',
        includes = '.',
        target = 'utils',
        install_path = None
    )

    bld.install_files('${PREFIX}/include', 'trap_utils.hpp customExceptions.hpp')
